name: Test Action Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test_results: ${{ steps.test-step-data.outputs.result }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Caching Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-cach-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Pass Data
        id: test-step-data
        run: echo "result=hello world" >> "$GITHUB_OUTPUT"

  build:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        - name: Caching Dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: npm-deps-cach-${{ hashFiles('**/package-lock.json') }}
        - name: Install Dependencies
          run: npm ci
        - name: Build
          run: npm run build
        - name: Save Artifact
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: dist
        - name: Get data
          run: echo "Data from Test Job ${{ needs.test.outputs.test_results }}"
  
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: download artifact
          uses: actions/download-artifact@v4
          with:
            name: dist-files
        - name: List files
          run: ls -ltr
        - name: Deploy
          run: echo "Deployment initiated"